imports:
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # knp_menu.voter.router.class: Knp\Menu\Matcher\Voter\RegexVoter

    
framework:
    secret: %kernel.secret%
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation: ~
    templating:
        engines: ['twig']
    translator: { fallbacks: ['%locale%'], logging: false }    

twig:
    globals:
        siteName: "Key Documents of German-Jewish History"
        slugify: "@cocur_slugify"
        webDir: "%kernel.root_dir%/../web"
        piwikSiteId: "%piwik.site_id%"
        
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host:     '%database.host%'
                port:     '%database.port%'
                dbname:   '%database.name%'
                user:     '%database.user%'
                password: '%database.password%'
                #driver:  pdo_mysql
                charset:  '%database.charset%' # UTF8
                options:
                        1002: "SET NAMES '%database.charset%' COLLATE '%database.charset%_unicode_ci'"
                default_table_options:
                    charset: %database.charset%
                    collate: '%database.charset%_unicode_ci'
                    engine:  MyISAM     # InnoDB
            admin:
                host:     '%database.host%'
                port:     '%database.port%'
                dbname:   'juedischegeschichte'
                user:     '%database.user%'
                password: '%database.password%'
                #driver:  pdo_mysql
                charset:  '%database.charset%' # UTF8
                options:
                        1002: "SET NAMES '%database.charset%' COLLATE '%database.charset%_unicode_ci'"
                default_table_options:
                    charset: %database.charset%
                    collate: '%database.charset%_unicode_ci'
                    engine:  MyISAM     # InnoDB
    orm:
        # TODO: set a cache, see http://www.craftitonline.com/2015/04/doctrine-file-system-caching-with-doctrine-cache-bundle/
        connection: default        
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true 

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        # see http://symfony.com/doc/current/cookbook/assetic/php.html
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            
jms_i18n_routing:
    default_locale: de
    locales: [de, en]
    strategy: custom
    hosts:
        de: %jms_i18n_routing.hosts.de%
        en: %jms_i18n_routing.hosts.en%
    redirect_to_host: true
    
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig
    
liip_url_auto_converter:
    linkclass:
    target: _blank
    debugmode: false

fs_solr:
    endpoints:
        jgo_presentation-de:
            host: localhost
            port: 8983
            path: /solr
            core: jgo_presentation-de
            timeout: 15
        jgo_presentation-en:
            host: localhost
            port: 8983
            path: /solr
            core: jgo_presentation-en
            timeout: 15
            
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        #distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        # pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template