imports:
    - { resource: config.yml }

framework:
    profiler:
        enabled: false # true by default
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE # DEBUG

# app/config/config.yml
fs_solr:
    endpoints:
        jgo_presentation-de:
            host: localhost
            port: 8983
            path: /solr
            core: jgo_presentation-de
            timeout: 15
        jgo_presentation-en:
            host: localhost
            port: 8983
            path: /solr
            core: jgo_presentation-en
            timeout: 15
            
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        #distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        # pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template