# app/config/services.yml
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: [@translator, @cocur_slugify]
        public: false
        tags:
            - { name: twig.extension }
            
    app.xslt_adapter:
        class:        "%app.xslt.adapter.class%"
        arguments:    [ "%app.xslt.adapter.arguments%" ]
        
    app.xslt:
        class:        AppBundle\Utils\Xsl\XsltProcessor
        calls:        
            - [setAdapter, ['@app.xslt_adapter']] 
